### ISSUE TITLE
Cannot read property 'name' of null" in `getModuleDistanceToRoot()`

### ISSUE THREAD

**Issue by clintharris** [sormy/systemjs-hot-reloader#2]
On some occasions I get the following error on hot-reload:

```
[HMR] Reloading file: js/views/FooComponent.js
[HMR] Reloading module ./js/views/FooComponent.js

SystemHotReloader.js:329 Uncaught (in promise) TypeError: Cannot read property 'name' of null
    at eval (http://localhost:9000/jspm_packages/npm/systemjs-hot-reloader-ex@2.0.4/SystemHotReloader.js:385:73
    at Array.reduce (native)
    at SystemHotReloader.getModuleDistanceToRoot (http://localhost:9000/jspm_packages/npm/systemjs-hot-reloader-ex@2.0.4/SystemHotReloader.js:384:37)
    at eval (http://localhost:9000/jspm_packages/npm/systemjs-hot-reloader-ex@2.0.4/SystemHotReloader.js:414:31)
    at Array.reduce (native)
    at SystemHotReloader.getReloadChain (http://localhost:9000/jspm_packages/npm/systemjs-hot-reloader-ex@2.0.4/SystemHotReloader.js:412:29)
    at SystemHotReloader.reloadModule (http://localhost:9000/jspm_packages/npm/systemjs-hot-reloader-ex@2.0.4/SystemHotReloader.js:155:30)
    at SystemHotReloader.reloadPath (http://localhost:9000/jspm_packages/npm/systemjs-hot-reloader-ex@2.0.4/SystemHotReloader.js:113:21)
    at http://localhost:9000/browser-sync/browser-sync-client.js?v=2.17.5:33:18

    (anonymous function)    @   SystemHotReloader.js:329
    getModuleDistanceToRoot @   SystemHotReloader.js:328
    (anonymous function)    @   SystemHotReloader.js:353
    getReloadChain  @   SystemHotReloader.js:351
    reloadModule    @   SystemHotReloader.js:123
    reloadPath  @   SystemHotReloader.js:89
    (anonymous function)    @   browser-sync-client.js?v=2.17.5:33
```

It's the highlighted line below, from `SystemHotReloader.js`:

```
key: 'getModuleDistanceToRoot',
value: function getModuleDistanceToRoot(name, record, cache) {
  var _this6 = this;

  var distance = void 0;
  if (cache[name] !== undefined) {
    return cache[name];
  }
  if (!record || !record.importers.length) {
    distance = 0;
  } else {
    distance = record.importers.reduce(function (result, impRecord) {
 -->     var impDistance = 1 + _this6.getModuleDistanceToRoot(impRecord.name, impRecord, cache);
      return result === null ? impDistance : Math.min(result, impDistance);
    }, null);
  }
  cache[name] = distance;
  return distance;
}
```

Any ideas as to what might be causing this? It doesn't happen consistently...

**Comment by sormy** [comment]
Does revert to backup works well in that case? Does it break next hot reloads?

**Comment by sormy** [comment]
impRecord is null. It is a sign of broken dependency tree.

I have a few ideas:

1) race condition, a few updates propagated as two hot reloads which executed almost in the same time (easily fixable)
2) something bad with hot reload logics, it could break dependency tree (need to reproduce to fix)

Let me know your thoughts. It will be perfect to have a small reproducible example so I will be able to fix it.

**Comment by clintharris** [comment]
Thanks for the leads. I'll try to see if I can isolate the conditions and create an example when I have time.

One scenario in which I consistently see the behavior is as follows...  Given `<Parent><Child/></Parent>` in which both components do _not_ have any state stuff--they simply render HTML:
1. Edit Child, hot-load, no problem
2. Edit Parent, hot-load, no problem
3. Edit Child, hot-load: **error** (reported above)

**Comment by sormy** [comment]
Ok, reproduced, looks like bug, will fix.

**Comment by sormy** [comment]
Ok, try v2.0.5 . Let me know if it helps.

**Comment by clintharris** [comment]
This fixed the issues--huge help. Thank you!
